### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [clragon/e1547#150]
**Describe the bug**
The .github/workflows/get_flutter_version.sh doesn't work. Could you please take a look? Thanks!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

 - Version [e.g. 1.0.0]

**Logs**

**Additional context**

**Comment by licaon-kter** [comment]
Can we reopen? Which Flutter version is used? https://gitlab.com/fdroid/fdroiddata/-/jobs/10286529484#L939

**Comment by clragon** [comment]
The bash script extracts the lower bound of the `flutter` key in the pubspec.yaml file.
At the moment this is `flutter: ">=3.32.0 <4.0.0"`, therefore `3.32.0` which is the current stable branch.

We can see that this version was used in my release runner:
```
Run subosito/flutter-action@v2
  with:
    flutter-version: 3.32.0
    cache: true
    channel: stable
    architecture: X64
    pub-cache-path: default
    dry-run: false
    git-source: https://github.com/flutter/flutter.git
  env:
    VERSION_BUMP: minor
    RELEASE_TITLE: everythings fixed now. promise.
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.15-6/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.15-6/x64
    FLUTTER_VERSION: 3.32.0
```
